name: ZAP Baseline Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan (no issue, no artifact)
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "http://example.com"
          rules_file_name: ""
          cmd_options: "-J report_json.json -w report_md.md -r report_html.html -a"
          # 🔑 Turn off auto issue creation & broken artifact upload
          allow_issue_writing: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP reports (safe)
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_html.html
            report_json.json
            report_md.md
