name: ZAP Baseline Scan

on:
  workflow_dispatch:   # allows manual trigger
  push:                # optional: runs on push
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "http://example.com"
          rules_file_name: ""
          cmd_options: "-J report_json.json -w report_md.md -r report_html.html -a"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Safe artifact upload (replace ZAP’s broken one)
      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_html.html
            report_json.json
            report_md.md
