name: ZAP Baseline Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan (manual, no auto-artifact)
        run: |
          docker run -v $(pwd):/zap/wrk/:rw --network=host ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://example.com \
            -J report_json.json -w report_md.md -r report_html.html -a

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_html.html
            report_json.json
            report_md.md
