name: ZAP Baseline

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP Baseline
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "http://example.com"   # change this later
          cmd_options: "-a"
          allow_issue_writing: false

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports   # ✅ changed from zap_scan to zap-reports
          path: |
            report_html.html
            report_md.md
            report_json.json
