name: ZAP Baseline

on:
  workflow_dispatch:   # allows manual run

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP Baseline
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://example.com'   # replace later with your DVWA if needed
          cmd_options: '-a'
